site_name: Unoriginal Prusa Connect Client SDK
edit_uri: https://github.com/dcode/python-prusa-connect-sdk-client/edit/main/docs/
theme:
  name: material
  favicon: img/favicon.png
  icon:
    logo: material/printer-3d
    edit: material/pencil
    view: material/eye
  palette:
    primary: deep orange # Matches Prusa branding
  features:
    - content.action.edit
    - content.code.copy
    - navigation.sections
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - markdown_gfm_admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
plugins:
  - search
  - optimize:
      enabled: false
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      enable_creation_date: true
      exclude:
      - index.md
  - cyclopts
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_submodules: true
            summary:
              attributes: false
              functions: true
              modules: true
  - git-committers:
      repository: dcode/python-prusa-connect-sdk-client
      branch: main
      enabled: !ENV [CI, false]
  - meta
  - typeset
exclude_docs: |
  development_notes/
extra_css:
  - css/extra.css
  - css/mkdocsoad.css
  - css/mkdocstrings.css
extra:
  analytics:
    provider: google
    property: G-TTT45413CN
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Authentication: authentication.md
  - CLI User Guide:
      - Quickstart: cli/quickstart.md
      - Reference: cli/reference.md
  - SDK Developer Guide:
      - Quickstart: sdk/quickstart.md
      - Examples: examples.md
      - API Reference:
          - Auth: api/auth.md
          - Client: api/client.md
          - Models: api/models.md
          - OpenAPI Reference: api/openapi-reference.md
  - Development Resources:
    - Contributing: CONTRIBUTING.md
    - Architecture Notes: internal_architecture.md
not_in_nav: |
  /api/index.md
