[project]
name = "prusa-connect"
version = "0.1.0"
description = "Prusa Connect CLI and API client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "rich>=14.3.1",
    "structlog>=25.5.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "better-exceptions>=0.3.3",
]

[project.scripts]
prusactl = "prusa_connect.cli:main"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]

[tool.hatch.build.targets.wheel]
packages = ["src/prusa_connect"]


[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

