# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint (${{ matrix.os }}, Python ${{ matrix.python-version }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Sync deps (frozen)
        run: uv sync --frozen --all-extras --all-groups
      - name: Use Hatch to build, lint, and typecheck
        run: |
          uv run hatch build
          uv run hatch fmt --check
          uv run hatch run typing:check
  test:
    name: Unit Tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Sync deps (frozen)
        run: uv sync --frozen --all-extras --all-groups
      - name: Use Hatch to test
        run: |
          uv run hatch test -py ${{ matrix.python-version }}
